Prevent Exception from being thrown when a disabled check is passed to `-XepPatchChecks`
PicnicSupermarket/error-prone pull request #62
Opened 2023-07-17 10:36 UTC by oxkitsune

This fix will prevent a `NoSuchElementException` being thrown when passing a disabled check to `-XepPatchChecks`.

Reproduction case: https://github.com/rickie/error-prone-demo/pull/2
Related issue: https://github.com/google/error-prone/issues/3908

2023-07-24 11:52 UTC, rickie requested changes
As discussed offline; we can probably add a test in the `ScannerSupplierTest.java` which makes it a lot easier to see what we are fixing. Additionally, it's nice to have a reproduction case in the code to quickly iterate. 

Added a commit 😄.

2023-07-24 11:52 UTC, rickie commented on check_api/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java
> +      // com.google.errorprone.scanner.ScannerSupplier#L210
Would omit this as it subject to change.

2023-07-24 11:52 UTC, rickie commented on check_api/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java
> +      // If the checker is still registered, attempting to report any matches will result in a a
```suggestion
      // If the checker is still registered, attempting to report any matches will result in a
```

2023-07-24 11:52 UTC, rickie commented on check_api/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java
> +      // When disabling a check using -Xep:<BugChecker>:OFF
In this project it occurs both; but especially with multi line (inline) comments we generally prefer `/* */` 😄. Seems nice here to me as well.

2023-07-24 11:52 UTC, rickie commented on check_api/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java
> +      // `com.google.errorprone.matchers.Description#severity()`.
I like the level of detail for the explanation, but I feel it doesn't belong here. It should be in the PR as extra context maybe, to make the reviewing easier though. (It helped me as well 😄).

I pushed a proposal for a one-liner explanation. PTAL 😄.

2023-07-26 08:01 UTC, oxkitsune commented on check_api/src/main/java/com/google/errorprone/BaseErrorProneJavaCompiler.java
> -import javax.tools.JavaCompiler.CompilationTask;
Not sure why this import got removed by IntelliJ's `Optimise imports`

2023-07-27 15:05 UTC, rickie approved these changes
Added a small commit. Really nice fix @oxkitsune 🚀 !

Suggested commit message:
```
Don't consider disabled checks passed to `-XepPatchChecks`

Fixes #3908.
```

Alternative suggested commit message:
```
Have `ScannerSupplier#applyOverrides` only consider enabled checks

Fixes #3908.
```
Consider could also be a different word like "modify" or "update". 

Not too happy with the suggestions, ideas welcome.

2023-07-27 15:05 UTC, rickie commented on core/src/test/java/com/google/errorprone/scanner/ScannerTest.java
> +  @Test
We can move this to the bottom of the class as we are adding it only now. Not a really good reason but it feels like the right thing to do?

2023-07-28 09:56 UTC, oxkitsune commented on core/src/test/java/com/google/errorprone/scanner/ScannerTest.java
> +  @Test
I wasn't exactly sure if this is the right file for the test, but I agree!

2023-07-30 10:00 UTC, Stephan202 approved these changes
Rebased and added a commit. Tweaked suggested commit message:
```
Ignore disabled checks passed to `-XepPatchChecks`

Rather than throwing an `NoSuchElementException`.

Fixes #3908.
```

2023-07-30 10:00 UTC, Stephan202 commented on check_api/src/main/java/com/google/errorprone/BaseErrorProneJavaCompiler.java
> -import javax.tools.JavaCompiler.CompilationTask;
On the one hand this is a nice cleanup, but it might also interfere with Google-internal code that is stripped out from the public repository. As such I'd keep it.

2023-07-30 10:00 UTC, Stephan202 commented on core/src/test/java/com/google/errorprone/scanner/ScannerTest.java
> +  public void dontRunDisabledChecks() {
How about:
```suggestion
  public void dontRunPatchForDisabledChecks() {
```

2023-07-31 10:49 UTC, oxkitsune commented
Upstream PR: https://github.com/google/error-prone/pull/4028

2025-01-03 17:49 UTC, closed without merging